### PR TITLE
Added new file for the acceptance gifs

### PR DESCRIPTION
**Pull request by theNafsters**
This file is to contain all the gifs needed for the wiki. The gifs can only be posted via URL and not from our local machines

### CODE REVIEW

**Comment by amneet270** [comment]
is there a way other to add the gifs on the repo except add URL on a read page

**Comment by obonobo** [comment]
Nafisa i think you can drag a gif file onto your wiki page and it will upload it into storage associated with the repo but not stored as a file in the repo itself

**Comment by obonobo** [comment]
like open file explorer and drag and drop does that work?

**Comment by obonobo** [comment]
@theNafsters Actually drag-and-drop doesn't seem to work.

But here is an alternative:

1. Go to wiki home page > bottom right > Clone this wiki locally

This will clone the wiki as a git repo

2. Add your GIF files

3. Create a link in your markdown that looks like:

```markdown
![My Pic](https://github.com/flapflapio/machinist-ui-test/wiki/mockup.PNG)
```

For example here is that link rendered in markdown (I uploaded a pic to the wiki - you can delete it if you want):

My Pic

**Pull request closed without merging**
